git:
  commitMessage: 'release: v${version}'
  tagName: v${version}
github:
  release: true
  releaseName: v${version}
plugins:
  '@release-it/conventional-changelog':
    preset: angular
    infile: CHANGELOG.md
    ignoreRecommendedBump: true
hooks:
  'before:init': 'pnpm test:fail'
