autoInstallPeers: false
strictPeerDependencies: true

allowBuilds:
  esbuild: true
  vue-demi: false

minimumReleaseAge: 2880
minimumReleaseAgeExclude:
  - '@globalbrain/*'
  - '@types/*'

overrides:
  jsdom: latest
