import { email } from 'sefirot/validation/validators'

describe('validation/validators/email', () => {
  test('it validates whether the value is email', () => {
    expect(email('someone@gmail.com')).toBe(true)
    expect(email('someone@g-mail.com')).toBe(true)
    expect(email('someone@g_mail.com')).toBe(true)
    expect(email('some!one@gmail.com')).toBe(true)
    expect(email('soMe12_one@gmail.com')).toBe(true)
    expect(email('someone@gmail.co')).toBe(true)
    expect(email('someone@g.cn')).toBe(true)
    expect(email('someone@g.accountants')).toBe(true)
    expect(email('"some@one"@gmail.com')).toBe(true)
    expect(email('"some one"@gmail.com')).toBe(true)
    expect(email('user.name+tag+sorting@example.com')).toBe(true)
    expect(email('"john..doe"@example.org')).toBe(true)
    expect(email('someone@Example.com')).toBe(true)

    expect(email(undefined)).toBe(false)
    expect(email(null)).toBe(false)
    expect(email(true)).toBe(false)
    expect(email(false)).toBe(false)
    expect(email(1)).toBe(false)
    expect(email({})).toBe(false)
    expect(email([])).toBe(false)
    expect(email('')).toBe(false)
    expect(email('12345')).toBe(false)
    expect(email('asdf12345')).toBe(false)
    expect(email(' ')).toBe(false)
    expect(email('someone@')).toBe(false)
    expect(email('someone@gmail')).toBe(false)
    expect(email('someone@gmail.')).toBe(false)
    expect(email('someone@gmail.c')).toBe(false)
    expect(email('gmail.com')).toBe(false)
    expect(email('@gmail.com')).toBe(false)
    expect(email('someone@g~mail.com')).toBe(false)
    expect(email('someone@g=ail.com')).toBe(false)
    expect(email('"someone@gmail.com')).toBe(false)
    expect(email('nonvalid±@gmail.com')).toBe(false)
    expect(email('joão@gmail.com')).toBe(false)
    expect(email('someõne@gmail.com')).toBe(false)
    expect(email('someone@gmail.com ')).toBe(false)
    expect(email('someone@gmail.com    ')).toBe(false)
    expect(email(' someone@gmail.com')).toBe(false)
    expect(email('some one@gmail.com')).toBe(false)
  })
})
